version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-image-name:latest
    container_name: your-container-name
    ports:
      - "3000:3000"
    volumes:
      - /home/martin/dev/task-frontend:/app
    restart: always
